title: Modernize This!
author: Alexia
email: olydevops@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Supporting government, nonprofit, and social enterprise IT shops looking to modernize technical practices and bring culture along for the ride

twitter_username: TypeErr0r
github_username:  alexiasa

sass:
    style: compressed